-- Nezapomeň na nastavení svého schématu, abys mohla vytvářet tabulky.
-- 1. ROLE -- zadejte svou roli
USE ROLE ROLE_CZECHITA_KOLAROVAM;
-- 2. WAREHOUSE
USE WAREHOUSE COMPUTE_WH;
-- 3. DATABASE
USE DATABASE COURSES;
-- 4. SCHEMA -- zadejte sve schema
USE SCHEMA SCH_CZECHITA_KOLAROVAM;

-- Nejdříve spoj IMDB_TITLES & IMDB_RATINGS (INNER JOIN) pomocí id (IMDB_TITLES.TCONST = IMDB_RATINGS.TCONST) do pomocné dočasné tabulky (CREATE TEMPORARY TABLE).
--> Zachovej pouze sloupce AVERAGERATING a NUMVOTES z tabulky IMDB_RATINGS

CREATE OR REPLACE TEMPORARY TABLE IMDB AS
SELECT
	AVERAGERATING,
	NUMVOTES,
	TITLETYPE,
	PRIMARYTITLE,
	ORIGINALTITLE,
	ISADULT,
	STARTYEAR,
	ENDYEAR,
	RUNTIMEMINUTES,
	GENRES
FROM COURSES.SCH_CZECHITA.IMDB_RATINGS AS IMDB_RATINGS
INNER JOIN COURSES.SCH_CZECHITA.IMDB_TITLES AS IMDB_TITLES
ON IMDB_RATINGS.TCONST = IMDB_TITLES.TCONST;


--> Zachovej všechny sloupce z IMDB_TITLES
CREATE OR REPLACE TEMPORARY TABLE EVERYTHING_2 AS
SELECT
    TCONST
    , TITLETYPE
    , PRIMARYTITLE
    , ORIGINALTITLE
    , ISADULT
    , STARTYEAR
    , ENDYEAR, RUNTIMEMINUTES
    , GENRES
    , __hevo__ingested_at
    , __hevo__marked_deleted
FROM SCH_CZECHITA.IMDB_TITLES;

--Pro napojení na Netflix potřebujeme vytvořit nový sloupeček, který upraví hodnoty ze sloupce TITLETYPE tak, abychom hodnoty mohly napojit na sloupeček TYPE z NETFLIX_TITLES.
--> Vytvoř v další pomocné tabulce (CREATE TEMPORARY TABLE) nový sloupeček TITLETYPE_NEW pomocí CASE WHEN.
--> V novém sloupečku bude hodnota 'Movie' pro hodnoty TITLETYPE 'movie', 'short', 'tvMovie', 'tvShort' a hodnota 'TV Show' pro hodnoty TITLETYPE 'tvSeries', 'tvMiniSeries'.
CREATE OR REPLACE TEMPORARY TABLE POMOCNA_TABULKA AS
SELECT
    TCONST AS TCONST_2
    , CASE
        WHEN TITLETYPE IN ('movie', 'short', 'tvMovie','tvShort') THEN 'Movie'
        WHEN TITLETYPE IN ('tvSeries', 'tvMiniSeries') THEN 'TV Show'
        ELSE 'EROR'
    END AS TITLETYPE_NEW
FROM SCH_CZECHITA.IMDB_TITLES;

CREATE OR REPLACE TEMPORARY TABLE EVERYTHING_4 AS
SELECT *
FROM EVERYTHING_3
INNER JOIN POMOCNA_TABULKA
ON EVERYTHING_3.TCONST = POMOCNA_TABULKA.TCONST_2;

ALTER TABLE EVERYTHING_4 DROP COLUMN TCONST_2;

SELECT * FROM EVERYTHING_4;

--Pomocnou tabulku s napojenými IMDB datasety a sloupečkem TITLETYPE a napojte pomocí INNER JOIN na NETFLIX_TITLES pomocí názvu, roku vydání a typu titulu a uložte do finální tabulky NETFLIX_IMDB (CREATE TABLE) 
--- a všechny sloupce z tabulky NETFLIX_TITLES
--(IMDB_TITLES.PRIMARYTITLE = NETFLIX_TITLES.TITLE 
-- AND IMDB_TITLES.STARTYEAR = NETFLIX_TITLES.RELEASE_YEAR
-- AND IMDB_TITLES.TITLETYPE_NEW = NETFLIX_TITLES.TYPE)
SELECT * FROM SCH_CZECHITA.NETFLIX_TITLES;

CREATE TABLE NETFLIX_IMDB AS
SELECT *
FROM SCH_CZECHITA.NETFLIX_TITLES;
INNER JOIN  EVERYTHING_4
ON EVERYTHING_4.PRIMARYTITLE = N_TITLES.TITLE AND EVERYTHING_4.STARTYEAR = N_TITLES_.RELEASE_YEAR AND EVERYTHING_4.TITLETYPE_NEW=N_TITLES_TITLES.TYPE;


SELECT COUNT(DISTINCT SHOW_ID)
FROM NETFLIX_IMDB;